const shoes_data = [
  {
    shoeImage: 'shoe_images/download.jpg',
    name: 'Jordan NOLA',
    brandName: 'Koryospor tysonter',
    gender: "Men's shoe",
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',
  },
  {
   shoeImage: 'shoe_images/7_823bce61-02ed-4032-8d10-5ea93ea2fff2.webp',
    name: 'AIr Jordan MVP 92',
    brandName: 'Ioryospor 3#otsonter',
    gender: 'For Men',
    actual_price: ' 2.195.00',
    discount: '0%',
    cur_price: '2.195.00',
  
  },
  {
     shoeImage: 'shoe_images/download (1).jpg',
    name: 'Air max plus',
    brandName: 'casual tysonter',
    gender: "Men's shoe",
    actual_price: ' 1.295.00',
    discount: '5%',
    cur_price: '9.95.00',
  },
  {
    shoeImage: 'shoe_images/images.jpg',
    name: 'Treaser *7 NOLA',
    brandName: 'Koryospor GYM Special ',
    gender: "Men's shoe",
    actual_price: ' 4.195.00',
    discount: '2%',
    cur_price: '4.005.00',
  },
  {
     shoeImage: 'shoe_images/images (57).jpg',
    name: 'JordanKIDs  NOLA',
    brandName: 'ryospor style tysonter',
    gender: 'Kids',
    actual_price: ' 2.895.00',
    discount: '15%',
    cur_price: '1.975.00',
  },
  {
      shoeImage: 'shoe_images/images (38).jpg',
    name: 'Women casula airOLA',
    brandName: 'tyerslon regonter',
    gender: "women's shoe",
    actual_price: ' 5.195.00',
    discount: '10%',
    cur_price: '4.205.00',
  },
  {
     shoeImage: 'shoe_images/images (60).jpg',
    name: 'Jordan NOLA',
    brandName: 'Kr kids  tysonter',
    gender: 'kids',
    actual_price: ' 7.105.00',
    discount: '12%',
    cur_price: '6.095.00',

  },
  {
     shoeImage: 'shoe_images/images (29).jpg',
    name: 'Air plus& NOLA',
    brandName: 'Gym EX03 tysonter',
    gender: "women's shoe",
    actual_price: ' 4.195.00',
    discount: '5%',
    cur_price: '3.899.00',

  },
  {
     shoeImage: 'shoe_images/images (26).jpg',
    name: 'Jordan NOLA',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',

  },
  {
     shoeImage: 'shoe_images/download (1).jpg',
    name: 'Easy XX teyr',
    brandName: 'rusnter EX tysonter',
    gender: "women's shoe",
    actual_price: ' 1.995.00',
    discount: '0%',
    cur_price: '1.995.00',

  },
  {
     shoeImage: 'shoe_images/download (2).jpg',
    name: 'Jordan XXX',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 4.195.00',
    discount: '40%',
    cur_price: '2.295.00',

  },
  {
     shoeImage: 'shoe_images/download (3).jpg',
    name: 'Brown Yonk',
    brandName: 'CasualSYtele tysonter',
    gender: "men's shoe",
    actual_price: ' 4.995.00',
    discount: '15%',
    cur_price: '3.295.00',

  },
  {
     shoeImage: 'shoe_images/images (21).jpg',
    name: 'CAuslak ret&s',
    brandName: 'oryos style tysonter',
    gender: "women's shoe",
    actual_price: ' 2.195.00',
    discount: '5%',
    cur_price: '1.995.00',

  },
  {
     shoeImage: 'shoe_images/images (22).jpg',
    name: 'Grill Rrtyer',
    brandName: 'Brons style ',
    gender: 'For Women',
    actual_price: ' 6.195.00',
    discount: '20%',
    cur_price: '5.295.00',

  },
  {
     shoeImage: 'shoe_images/images (23).jpg',
    name: 'Jordan NOLA',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',

  },
  {
     shoeImage: 'shoe_images/images (42).jpg',
    name: 'Yter plus+ OLA',
    brandName: 'creamy SYlyor',
    gender: 'For Women',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',

  },
  {
     shoeImage: 'shoe_images/images (43).jpg',
    name: 'Air plus Jordan',
    brandName: 'STuleyospor ysonter',
    gender: 'kids',
    actual_price: ' 2.195.00',
    discount: '0%',
    cur_price: '2.195.00',

  },
  {
     shoeImage: 'shoe_images/images (44).jpg',
    name: 'JA YSTer',
    brandName: 'kids on STyele',
    gender: 'Kids',
    actual_price: ' 4.195.00',
    discount: '30%',
    cur_price: '2.995.00',
  },
  {
     shoeImage: 'shoe_images/images (24).jpg',
    name: 'WOmen syyekle LA',
    brandName: 'suebr ysonter',
    gender: 'For Women',
    actual_price: ' 4.195.00',
    discount: '10%',
    cur_price: '3.995.00',
  },
  {
     shoeImage: 'shoe_images/images (1).jpg',
    name: 'JmenOLA',
    brandName: 'ON WHITE Sy ',
    gender: 'For Men',
    actual_price: ' 7.195.00',
    discount: '25%',
    cur_price: '6.005.00',
  },
  {
     shoeImage: 'shoe_images/images (4).jpg',
    name: 'Rordan ##LA',
    brandName: 'KLUTER sonter',
    gender: 'For Men',
    actual_price: ' 5.995.00',
    discount: '5%',
    cur_price: '5.115.00',
  },
  {
     shoeImage: 'shoe_images/images (3).jpg',
    name: 'BLACK ON ',
    brandName: 'por YT#sonter',
    gender: 'For Men',
    actual_price: ' 3.195.00',
    discount: '0%',
    cur_price: '3.195.00',
  },
  {
     shoeImage: 'shoe_images/images (5).jpg',
    name: 'JS GYM REUning',
    brandName: 'gym style grey',
    gender: 'For Men',
    actual_price: ' 9.195.00',
    discount: '30%',
    cur_price: '8.095.00',
  },
  {  shoeImage: 'shoe_images/images (6).jpg',
    name: 'CAsual ##A',
    brandName: 'K9908 nter',
    gender: 'For Men',
    actual_price: ' 6.999.00',
    discount: '15%',
    cur_price: '5.908.00',
  },
  {  shoeImage: 'shoe_images/images (20).jpg',
    name: 'Jordan NOLA',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 6.195.00',
    discount: '12%',
    cur_price: '5.295.00',
  },
  {
      shoeImage: 'shoe_images/images (25).jpg',
    name: 'WMONW WHite',
    brandName: 'shuetwnee ##8976ysonter',
    gender: 'For Women',
    actual_price: ' 2.195.00',
    discount: '10%',
    cur_price: '2.003.00',
  },
  {
    shoeImage: 'shoe_images/images (40).jpg',
    name: 'PInk NOLA',
    brandName: 'Causualr tysonter',
    gender: 'For Women',
    actual_price: ' 2.195.00',
    discount: '5%',
    cur_price: '2.695.00',
  },
  {
      shoeImage: 'shoe_images/images (27).jpg',
    name: 'EXdan NOLA',
    brandName: 'Iuyspor tysonter',
    gender: 'For Women',
    actual_price: ' 6.195.00',
    discount: '20%',
    cur_price: '5.010.00',
  },
  {
      shoeImage: 'shoe_images/images (28).jpg',
    name: 'AIr Jordan NOLA',
    brandName: 'haoemospor tysonter',
    gender: 'For Women',
    actual_price: ' 2.195.00',
    discount: '15%',
    cur_price: '1.995.00',
  },
  {
      shoeImage: 'shoe_images/images (18).jpg',
    name: 'PLus %$$ UYA',
    brandName: 'noweoryospor tysonter',
    gender: 'For Men',
    actual_price: ' 7.195.00',
    discount: '30%',
    cur_price: '5.295.00',
  },
  {
      shoeImage: 'shoe_images/images (45).jpg',
    name: 'KUASw NOLA',
    brandName: 'SYleiw Kids tysonter',
    gender: 'kids',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',
  },
  {
      shoeImage: 'shoe_images/images (46).jpg',
    name: 'WHite NOLA',
    brandName: 'asnodporHWIte tysonter',
    gender: 'kids',
    actual_price: ' 4.195.00',
    discount: '5%',
    cur_price: '3.995.00',
  },
  {
      shoeImage: 'shoe_images/images (47).jpg',
    name: 'Jordan NOLA',
    brandName: 'Koryospor tysonter',
    gender: 'kids',
    actual_price: ' 2.195.00',
    discount: '15%',
    cur_price: '1.785.00',
  },
  {
      shoeImage: 'shoe_images/images (48).jpg',
    name: 'YUER amksA',
    brandName: 'amksdor Mnter',
    gender: 'kids',
    actual_price: ' 3.195.00',
    discount: '15%',
    cur_price: '2.995.00',
  },
  {
      shoeImage: 'shoe_images/images (7).jpg',
    name: 'NDKan MKFDA',
    brandName: 'sdmf m&nter',
    gender: 'For Men',
    actual_price: ' 8.195.00',
    discount: '20%',
    cur_price: '7.295.00',
  },
  {
      shoeImage: 'shoe_images/images (8).jpg',
    name: 'PLus NOLA',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 2.995.00',
    discount: '25%',
    cur_price: '2.105.00',
  },
  {
      shoeImage: 'shoe_images/images (30).jpg',
    name: 'Black Jordan NOLA',
    brandName: 'msdoospor meonter',
    gender: 'For Women',
    actual_price: ' 4.195.00',
    discount: '10%',
    cur_price: '3.995.00',
  },
  {
      shoeImage: 'shoe_images/images (31).jpg',
    name: 'WomenJordan NOLA',
    brandName: 'MDOspor FMDonter',
    gender: 'For Women',
    actual_price: ' 5.195.00',
    discount: '20%',
    cur_price: '4.295.00',
  },
  {
      shoeImage: 'shoe_images/images (49).jpg',
    name: 'Red AireNOLA',
    brandName: 'Rfdimwo sdmlw',
    gender: 'Kids',
    actual_price: ' 2.995.00',
    discount: '5%',
    cur_price: '2.395.00',
  },
  {
      shoeImage: 'shoe_images/images (50).jpg',
    name: 'PInan YTELA',
    brandName: 'asndkwor nesonter',
    gender: 'kids',
    actual_price: ' 3.195.00',
    discount: '15%',
    cur_price: '2.995.00',
  },
  {
      shoeImage: 'shoe_images/images (45).jpg',
    name: 'KUASw NOLA',
    brandName: 'SYleiw Kids tysonter',
    gender: 'kids',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',
  },

  {
      shoeImage: 'shoe_images/images (10).jpg',
   name: 'MenSTYEL ON ',
    brandName: 'por YT#sonter',
    gender: 'For Men',
    actual_price: ' 3.195.00',
    discount: '0%',
    cur_price: '3.195.00',
  },
  {
      shoeImage: 'shoe_images/images (9).jpg',
     name: 'Black Yonk',
    brandName: 'CasualSYtele tysonter',
    gender: "men's shoe",
    actual_price: ' 4.995.00',
    discount: '15%',
    cur_price: '3.295.00',
  },
  {
      shoeImage: 'shoe_images/images (11).jpg',
    name: 'Jordan XXX',
    brandName: 'Koryospor tysonter',
    gender: 'For Men',
    actual_price: ' 4.195.00',
    discount: '40%',
    cur_price: '2.295.00',
  },
  {
      shoeImage: 'shoe_images/images (12).jpg',
   name: 'JA YSTer',
    brandName: 'kids on STyele',
    gender: 'Kids',
    actual_price: ' 4.195.00',
    discount: '30%',
    cur_price: '2.995.00',
  },
  {
      shoeImage: 'shoe_images/images (13).jpg',
    name: 'Jmen MI LA',
    brandName: 'ON WHITE Sy ',
    gender: 'For Men',
    actual_price: ' 7.195.00',
    discount: '25%',
    cur_price: '6.005.00',
  },
  {
      shoeImage: 'shoe_images/images (14).jpg',
    name: 'AIr Jordan MVP 92',
    brandName: 'Ioryospor 3#otsonter',
    gender: 'For Men',
    actual_price: ' 2.195.00',
    discount: '0%',
    cur_price: '2.195.00',
  },
  {
      shoeImage: 'shoe_images/images (15).jpg',
   name: 'Treaser *7 NOLA',
    brandName: 'Koryospor GYM Special ',
    gender: "Men's shoe",
    actual_price: ' 4.195.00',
    discount: '2%',
    cur_price: '4.005.00',
  },
  {
      shoeImage: 'shoe_images/images (51).jpg',
   name: 'Jordan NI Plus',
    brandName: 'Kr kids  tysonter',
    gender: 'kids',
    actual_price: ' 7.105.00',
    discount: '12%',
    cur_price: '6.095.00',
  },
  {
      shoeImage: 'shoe_images/images (52).jpg',
    name: 'YUER amksA',
    brandName: 'amksdor Mnter',
    gender: 'kids',
    actual_price: ' 3.195.00',
    discount: '15%',
    cur_price: '2.995.00',
  },
  {
    shoeImage: 'shoe_images/images (31).jpg',
    name: 'WOmen syyekle LA',
    brandName: 'suebr ysonter',
    gender: 'For Women',
    actual_price: ' 4.195.00',
    discount: '10%',
    cur_price: '3.995.00',
  },
  {
      shoeImage: 'shoe_images/images (33).jpg',
    name: 'WMONW WHite',
    brandName: 'shuetwnee ##8976ysonter',
    gender: 'For Women',
    actual_price: ' 6.895.00',
    discount: '10%',
    cur_price: '6.003.00',
  },
  {
      shoeImage: 'shoe_images/images (53).jpg',
     name: 'JordanKIDs  NOLA',
    brandName: 'ryospor style tysonter',
    gender: 'Kids',
    actual_price: ' 2.895.00',
    discount: '15%',
    cur_price: '1.975.00',
  },
  {
      shoeImage: 'shoe_images/images (34).jpg',
    name: 'Yter plus+ OLA',
    brandName: 'creamy SYlyor',
    gender: 'For Women',
    actual_price: ' 3.195.00',
    discount: '10%',
    cur_price: '2.295.00',
  },
  {
      shoeImage: 'shoe_images/images (16).jpg',
   name: 'sdbjual ##A',
    brandName: 'K9908 nter',
    gender: 'For Men',
    actual_price: ' 6.999.00',
    discount: '15%',
    cur_price: '5.908.00',
  },
  {
      shoeImage: 'shoe_images/images (35).jpg',
    name: 'CAuslak ret&s',
    brandName: 'oryos style tysonter',
    gender: "women's shoe",
    actual_price: ' 2.195.00',
    discount: '5%',
    cur_price: '1.995.00',
  },
  {
      shoeImage: 'shoe_images/images (59).jpg',
    name: 'Pink plus Jordan',
    brandName: 'STuleyospor ysonter',
    gender: 'kids',
    actual_price: ' 2.195.00',
    discount: '0%',
    cur_price: '2.195.00',
  },
  {
      shoeImage: 'shoe_images/images (37).jpg',
     name: 'CAuslak ret&s',
    brandName: 'oryos style tysonter',
    gender: "women's shoe",
    actual_price: ' 2.195.00',
    discount: '5%',
    cur_price: '1.995.00',
  },
  {
      shoeImage: 'shoe_images/images (36).jpg',
    name: 'Grill Rrtyer',
    brandName: 'Brons style ',
    gender: 'For Women',
    actual_price: ' 6.195.00',
    discount: '20%',
    cur_price: '5.295.00',
  },
  {
      shoeImage: 'shoe_images/images (17).jpg',
    name: 'Rordan ##LA',
    brandName: 'KLUTER sonter',
    gender: 'For Men',
    actual_price: ' 5.995.00',
    discount: '5%',
    cur_price: '5.115.00',
  }
]
